process_dataset: ArgmaxDataset
epochs: 100
subset:
  - 0.05
  - 0.1
  - 0.2
  - 0.5
  - 0.9
check_every: 20
first_eval: 1
save_data: True
duplication: 0
subfeasible: False
train_margin_accuracy: False
test_margin_accuracy: True
loss_per_epoch: True
test_accuracy_per_epoch: True
train_accuracy_per_epoch: False
accuracy_per_epoch_threshold: 0.05
lookup: True