process_dataset: LourencoDataset
subset:
  - 0.9
n: 0.15
K: 40
epochs: 100
check_every: 20
first_eval: 1
save_data: True
train_margin_accuracy: False
test_margin_accuracy: True
loss_per_epoch: True
test_accuracy_per_epoch: True
train_accuracy_per_epoch: False
lookup: False