subset:
  - 0.05
  - 0.1
  - 0.2
  - 0.5
  - 0.9
save_data: True
duplication: 0
subfeasible: False
train_margin_accuracy: False
test_margin_accuracy: True
loss_per_epoch: False
test_accuracy_per_epoch: False
train_accuracy_per_epoch: False
lookup: False
basedata: False