process_dataset: ArgmaxDataset
model: 500GELU
loss: L1Loss
subset:
  - 0.05
  - 0.1
  - 0.2
  - 0.5
  - 0.9
save_data: True
duplication: 0
subfeasible: False
margin_accuracy: True
loss_per_epoch: False
accuracy_per_epoch: False
lookup: False