test_netlist: pa/pa-test.sp
parameter_list:
  # - pa-lint #const
  # - pa-ls1  #const
  # - pa-ls2 #const
  - pa-vb1
  - pa-vb2
  - pa-w1
  - pa-w2
performance_list:
  - pa-gain1
  - pa-PAE1
  - pa-DE1
order:
  - 0
  - 2
  - 1
sign:
  - 1
  - 1
  - 1
arguments:
  model_path: config/model/45nm_CS.pm
  # pa-lint_start: 160p
  # pa-lint_stop: 160p #170p
  # pa-lint_change: 5p ##
  # pa-ls1_start: 450p
  # pa-ls1_stop: 450p #470
  # pa-ls1_change: 5p
  # pa-ls2_start: 480p #470
  # pa-ls2_stop: 480p
  # pa-ls2_change: 5p ##
  pa-vb1_start: 785m
  pa-vb1_stop: 815m
  pa-vb1_change: 5m
  pa-vb2_start: 760m
  pa-vb2_stop: 790m
  pa-vb2_change: 5m
  pa-w1_start: 18u
  pa-w1_stop: 22u
  pa-w1_change: 0.5u
  pa-w2_start: 27u
  pa-w2_stop: 34.5u
  pa-w2_change: 1u
  out: data/pa



