dataset:
  - type: Ablation
  - type: Argmax
  - type: Lourenco
  - type: SoftArgmax
  - type: SoftBase
metric: absolute
model_config:
  - model: Model500GELU
rerun_training: False
device: cpu
check_circuit: False
num_sample_check: 8
random_sample_scale: 1.5
log_experiments: False
simulator_config:
  num_workers: 8
  sim_size: 100
  multiprocessing: True
epsilon: 0.2
subset:
  - 0.9
circuits:
  - nmos
  - lna
  - cascode
  - mixer
  - vco
  - pa
  - two_stage
loss_per_epoch: True
test_accuracy_per_epoch: True
train_accuracy_per_epoch: False
compare_dataset: True
compare_method: False
subset_percentage: 1.0
mode: replace