dataset:
  - type: SoftArgmax
metric: absolute
model_config: 
  - model: Model500GELU
rerun_training: True
device: cpu
check_circuit: True
num_sample_check: 8
random_sample_scale: 1.5
log_experiments: False
simulator_config:
  num_workers: 8
  sim_size: 100
  multiprocessing: True
epsilon: 0.2
subset:
  - 0.05
  - 0.1
  - 0.2
  - 0.5
  - 0.9
circuits:
  - nmos
  - lna
  - cascode
  - mixer
  - vco
  - pa
  - two_stage
loss_per_epoch: False
test_accuracy_per_epoch: False
train_accuracy_per_epoch: False
compare_dataset: False
compare_method: False