conflict_rule:
  - type: Boolean
    pipeline: SklearnPipeline
    key: train_accuracy_per_epoch
    value: False
  - type: Boolean
    pipeline: SklearnPipeline
    key: test_accuracy_per_epoch
    value: False
  - type: Boolean
    pipeline: SklearnPipeline
    key: loss_per_epoch
    value: False
  - type: Boolean
    pipeline: LourencoPipeline
    key: lookup
    value: False