pipeline: SklearnPipeline #SklearnPipeline #CrossFoldValidationPipeline
model_config: 
  model: RandomForestRegressor #RandomForestRegressor #Model500GELU
evaluation_same_distribution: True
circuit: vco
rerun_training: False
device: cpu
check_circuit: True
num_sample_check: 8
random_sample_scale: 1.5
log_experiments: False
simulator_config:
  num_workers: 8
  sim_size: 100
subset:
  # - 2
  # - 3
  # - 5
  # - 8
  # - 10
  # - 0.05
  # - 0.1
  # - 0.2
  - 0.5
  # - 0.9