pipeline: CrossFoldValidationPipeline
circuit: vco
rerun_training: False
device: cpu
check_circuit: True
num_sample_check: 8
random_sample_scale: 1.5
log_experiments: True
subset:
  - 0.2
  - 0.5
  - 0.9