dataset:
  - type: Argmax
model_config:
  - model: RandomForestRegressor #RandomForestRegressor #Model500GELU
metric: absolute
rerun_training: True
device: cpu
check_circuit: True
num_sample_check: 8
random_sample_scale: 1.5
log_experiments: False
simulator_config:
  num_workers: 8
  sim_size: 100
  multiprocessing: True
epsilon: 0.3
subset:
  - 0.9
circuits:
  - pa
compare_dataset: False
compare_method: False