pipeline: SklearnPipeline #SklearnPipeline #CrossFoldValidationPipeline #LourencoSklearnPipeline LourencoPipeline
dataset: Argmax #Argmax #SoftArgmax #Lourenco #Base #Ablation
model_config:
  model: RandomForestRegressor #RandomForestRegressor #Model500GELU
metric: absolute
evaluation_same_distribution: False
rerun_training: False
device: cpu
check_circuit: True
num_sample_check: 8
random_sample_scale: 1.5
log_experiments: False
simulator_config:
  num_workers: 8
  sim_size: 100
  multiprocessing: True
epsilon: 0.3
subset:
  - 0.05
  - 0.1
  - 0.2
  - 0.5
  - 0.9