test_netlist: VCO/VCO.sp
parameter_list:
  - vco-wn
  - vco-wt
  - vco-wv
  - vco-lt
performance_list:
  - vco-power_consumption
  - vco-out_power
  - vco-tuningrange
order:
  - 0
  - 1
  - 2
sign:
  - -1
  - 1
  - 1
arguments:
  model_path: config/model/45nm_CS.pm
  vco-wn_start: 117u
  vco-wn_stop: 124u
  vco-wn_change: 1u
  vco-wt_start: 145u
  vco-wt_stop: 159u
  vco-wt_change: 2u
  vco-wv_start: 73u
  vco-wv_stop: 87u
  vco-wv_change: 2u
  vco-lt_start: 3.6n
  vco-lt_stop: 4.4n
  vco-lt_change: 0.1n
  out: data/VCO

  