test_netlist: cascode/nmos-testing-cascode.sp
parameter_list:
  - cascode-r
  - cascode-w0
  - cascode-w1
performance_list:
  - cascode-bw
  - cascode-pw
  - cascode-a0
order:
  - 0
  - 2
  - 1
sign:
  - 1
  - -1
  - 1
arguments:
  model_path: config/model/45nm_CS.pm
  cascode-w0_start: 8u
  cascode-w0_stop: 11.5u
  cascode-w0_change: 0.25u
  cascode-w1_start: 2u
  cascode-w1_stop: 5u
  cascode-w1_change: 0.2u
  cascode-r_start: 9000
  cascode-r_stop: 11000
  cascode-r_change: 125
  out: data/cascode