test_netlist: mixer/Mixer-test.sp
parameter_list:
  - mixer-vbrf
  - mixer-rl
  - mixer-wn
  - mixer-wt
performance_list:
  - mixer-PowerConsumption
  - mixer-Swing
  - mixer-Conversion_Gain
order:
  - 0
  - 2
  - 1
sign:
  - -1
  - 1
  - 1
arguments:
  model_path: config/model/45n270AModels.pm
  mixer-vbrf_start: 600m
  mixer-vbrf_stop: 810m
  mixer-vbrf_change: 30m
  mixer-rl_start: 240
  mixer-rl_stop: 520
  mixer-rl_change: 40
  mixer-wn_start: 8.55u
  mixer-wn_stop: 11.70u
  mixer-wn_change: 0.45u
  mixer-wt_start: 17.1u
  mixer-wt_stop: 23.4u
  mixer-wt_change: 0.9u
  out: data/mixer